### ISSUE TITLE
Versioning Questions

### ISSUE THREAD

**Issue by jongio** [3MFConsortium/spec_core#36]
1. When I crack open a 3mf file.  Where do I find the version number? I was expecting it to be in 3dmodel.model file

1. Does that version number map to the schema or to the version number listed on this site? i.e. 1.2.3 or 1.2.4 or http://schemas.microsoft.com/3dmanufacturing/core/2015/02

1. Is there a location where I can find the full history of versioning information?  As in, release notes for each version?

**Comment by jordig100** [comment]
Unfortunately the version number is not in the 3MF document. A specific namespace might support several versions with compatible schemas.
Adding new functionality to a spec might require the create an addicional namespace in order to select that functionality. See as an example the Balls addition in the Beam Lattices spec.
